# Generated by Django 4.2.7 on 2023-11-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
